apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubearmor-operator-scc-privileged-v1
subjects:
- kind: ServiceAccount
  name: kubearmor-operator
  namespace: openshift-operators
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:privileged
  apiGroup: rbac.authorization.k8s.io